# Generated by Django 3.0.2 on 2020-04-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=255)),
                ('uz', models.CharField(max_length=255)),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('max_ask', models.IntegerField(default=10)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicts', to='quiz.Theme')),
            ],
        ),
    ]
