# Generated by Django 3.0.2 on 2020-05-08 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='max_ask',
            new_name='min_ask',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='type',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'public')], default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
