# Generated by Django 3.0.2 on 2020-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200508_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='type',
        ),
        migrations.AddField(
            model_name='theme',
            name='type',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'public')], default=0),
        ),
    ]
